steps:
  # STEP 1: Mengambil file .env dari Google Cloud Storage
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "gs://plant-tpm/.env", ".env"]

  # STEP 2: Build Docker image dari root folder
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/backend", "."]

  # STEP 3: Push Docker image ke Google Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/backend"]

  # STEP 4: Deploy ke Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "plant-parent-helper-be",
        "--image",
        "gcr.io/$PROJECT_ID/backend",
        "--timeout",
        "1000s",
        "--port",
        "5000",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

options:
  logging: CLOUD_LOGGING_ONLY
